server:
  port: 8088
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  ######################################
  #
  # ?????????
  #
  ######################################
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xbxxz?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: Zhaojialin@666
    hikari:
      # ???????????????????
      pool-name: DataSourceHikariCP
      # ?????????????????????????????
      connection-timeout: 30000
      # ??????????????????????????
      minimum-idle: 5
      # ?????????????????????????????
      maximum-pool-size: 20
      # ???????true????????????false????????
      auto-commit: true
      # ???????????????????????????
      idle-timeout: 600000
      # ???????????????????????????????
      max-lifetime: 1800000
######################################
# application.yml
# API??????-??swagger3??????

# Springfox
# Swagger
######################################
springfox:
  documentation:
    swagger-ui:
      enabled: true
knife4j:
  setting:
    enableSwaggerModels: true

